version: '2'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  db_postgres:
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  webspoon:
    image: hiromuhota/webspoon
    user: root
    ports:
      - "8082:8080"
    volumes:
      - ./arquivos:/home/arquivos
      - kettle:/home/tomcat/.kettle
      - pentaho:/home/tomcat/.pentaho
    environment:
      - "JAVA_OPTS=-Xms1024m -Xmx2048m"
    links:
      - db_postgres

volumes:
  kettle:
  pentaho:
